[auth]
cookie_name = "unvisited_dashboard"
cookie_key = "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_123456789"
cookie_expiry_days = 7

[auth.users.admin]
name = "Admin"
password = "$2b$12$XVDEhc2gFT8/Dfos5hNh4.1PMzCBpvRKs5g5br5RqeA0E2Qk7tnGW"

[auth.users.manager]
name = "Manager"
password = "$2b$12$XVDEhc2gFT8/Dfos5hNh4.1PMzCBpvRKs5g5br5RqeA0E2Qk7tnGW"
